name: ArGlass

options:
  bundleIdPrefix: com.fumiya-kume
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1

targets:
  ArGlass:
    type: application
    platform: iOS
    sources:
      - path: ArGlass
    resources:
      - path: ArGlass/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fumiya-kume.arglass
        INFOPLIST_FILE: ArGlass/Resources/Info.plist
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: R5YS6ZB47G

schemes:
  ArGlass:
    build:
      targets:
        ArGlass: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

