name: ArGlass

options:
  bundleIdPrefix: com.fumiya-kume
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    MARKETING_VERSION: 0.1.0
    CURRENT_PROJECT_VERSION: 1

targets:
  ArGlass:
    type: application
    platform: iOS
    sources:
      - path: ArGlass
    resources:
      - path: ArGlass/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fumiya-kume.arglass
        INFOPLIST_FILE: ArGlass/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: ArGlass/ArGlass.entitlements
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: R5YS6ZB47G

  ArGlassTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ArGlassTests
    dependencies:
      - target: ArGlass
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fumiya-kume.arglass.tests
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: R5YS6ZB47G
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ArGlass.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/ArGlass"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: true

schemes:
  ArGlass:
    build:
      targets:
        ArGlass: all
        ArGlassTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - ArGlassTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
